### ISSUE TITLE
Cover photo

### ISSUE THREAD

**Issue by jitka** [Kedrigern/blog#11]
Nápady (píše Jitka a Ondra)
- poslanec  by mohlo už plynule splívat ze spodem mapy
- celkově to může být širší (jako texty+fotka) nebo nemít okolo té fotky bílé mezery
    nebo mít text vlevo průhledný a přes fotku v pravo které by se přes sebe plynule přesouvali
   (ale to je taková chuťovka na později)
- jiný font, který by byl bližši zbytku stránky
- nápady na dalši slova: opendata, bigdata, linux, UX

**Comment by matejsoukup** [comment]
Zkusil jsem to. Jetě  možná s tou barvou a průhledností by se dalo vyhrát.
