### ISSUE TITLE
Page: Transparentnost

### ISSUE THREAD

**Issue by Kedrigern** [Kedrigern/blog#2]
Obsah stránky:

- Hlasování poslance: http://www.psp.cz/sqw/hlasovani.sqw?id=6526
- Výroční zprávy klubu Pirátů v ZHMP: [2015](https://github.com/pirati-cz/KlubPraha/blob/master/materialy/vyrocni-zprava/vyrocni-zprava.pdf), [2016](https://github.com/pirati-cz/KlubPraha/blob/master/materialy/vyrocni-zprava-2016/vyrocni-zprava-2016.pdf)
- Kalendář (jako na pirati.cz/lide/ondrej-profant)

**Comment by matejsoukup** [comment]
Hotovo, vše je v page/transparentnost.md
