### ISSUE TITLE
SEO a social media integrace

### ISSUE THREAD

**Issue by Kedrigern** [Kedrigern/blog#5]
Je třeba:

1. Nasadit plugin, který generuje `sitemap.xml` a odkázat tento soubor z hlavičky
2. Každá stranka musí mít smysluplně vyplněné klasické meta tagy
3. Každá stránka musí mít opengraph meta tagy (FB), ty se kontrolují skrze: https://developers.facebook.com/tools/debug/sharing/

Všechny tyto věci by měly být vyřešeny na pirati.cz, čili se lze inspirovat.

**Comment by matejsoukup** [comment]
hotovo
